version: "3.9"

services:
  database:
    image: postgres
    container_name: queries_challenge
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local